### ISSUE TITLE
submission app: click boxes to create customized template

### ISSUE THREAD

**Issue by dklinges9** [Smithsonian/CCRCN-Data-Library#11]
the user select checkboxes, etc. and can then download a customized set of templates. JH and DK have discussed this before.

**Comment by HolmquistJ** [comment]
I was thinking about this, and we should have tabs for all study-level meta-data. Sort of a choose your own adventure, where we ask about what data types are there, and ask method specific questions. 

First few tabs would be like, add all author names, keywords, abstract, add bibtex for associated publications. 

Tabs asking about site data and core data ask whether positional data refers to site or cores, whether species, salinity, and impact data refer to sites or cores, how species, and salinity were determined. How position was determined, whether they tracked uncertainty in lat-long.

When you get to methods you would "check all boxes for data that's available: loss-on-ignition, carbon content, bulk density, accretion rates". Some boxes you click would give you a drop down with further methods questions, or further boxes to click. 

* Loss-on-ignition
  + What temperature?
  + Amount of time?
    - Precise Entry
    - Qualitative Note
* Bulk Density 
  + What temperature?
  + Amount of time?
    - Precise Entry
    - Qualitative Note
* Loss on ignition OR Bulk Density
  + Sample Size
  +  Mass or Volume Units
* Accretion Rate
  + 137Cs
    - Gamma or Alpha
    - Uncertainty Measured?
  + 210Pb
    - Gamma or Alpha
    - Uncertainty Measured?
  + 14C
  + Miscelaneous Horizons

This is a non-comprehenisive snippet of what a longer set of choices would be. Bottom line is that this page would both do the data entry of the method meta data table, and determine what attributes to include in the templates they download.

The templates the user downloads will be site, core, and depth series data. Users would download the csvs, fill them out, upload the data, and get their uploads checked by some automated scripts, probably some of the same basics that we would use for hook scripts, to make sure things are complete.

**Comment by HolmquistJ** [comment]
I was also thinking we could use this methods meta-data page in the app not only for formatting new data releases but also for adding detail to existing entries. Maybe the app has two settings: upload data source, or add detailed to existing entry. For example, a lot of sanderman data does not have good enough methods metadata coding. 

We could code methods metadata quality as it stands from level 3 (incomplete), to 2 (complete but not checked) to 1 (complete and checked by multiple parties). 

We could get people from the community to help fill these out methods metadata entry and offer coauthorship on a community methods meta-analysis paper in exchange for leveling up a certain number of data entries.
