### ISSUE TITLE
couldn't get mutate + ifelse to work?

### ISSUE THREAD

**Issue by dklinges9** [Smithsonian/CCRCN-Data-Library#12]
This is a personal issue and frustration that doesn't have bearing on the function of the repo. I just want to ask the world (read: @mlonneman) why.

Check out [here](https://github.com/Smithsonian/CCRCN-Data-Library/blob/95f8a005d4e333054e2a4b104476cb247f333f1a/scripts/0_data_hooks/Holmquist_2018_hook.R#L72) in the Holmquist 2018 hook:

```
# There's a typo with Galveston Bay sites. For some reason mutate + ifelse 
# was giving me issues.
cores$site_id <- recode(cores$site_id, "Gavelston_Bay" = "Galveston_Bay")
```

As the comment notes, I couldn't get this to work:
```
cores <- cores %>%
# if site_id is improperly labeled "Gavelston_Bay" (which is a typo), re-label "Galveston_Bay".   
# Otherwise keep the same site_id
mutate(site_id = ifelse(site_id == "Gavelston_Bay", "Galveston_Bay", site_id)
```

Replacing the typo would work fine...but every other site_id was changed to a number. Not sure what the number was, it wasn't the row index. Confusing. If you're curious want to check it out?

**Comment by ktoddbrown** [comment]
Is it a casting issue? If site_id was a factor and then you added a string as the return to the ifelse - true section then R might have done something strange. Factors are actually enumerated classes so R thinks they are a number internally and will occasionally loose their key when trying to move across classes. dplyr::if_else forces the same class returns in both the true and false evaluation and will avoid this. 

The recode is actually a cleaner solution I think but maybe try 
`mutate(site_id = recode(site_id, "Gavelston_Bay" = "Galveston_Bay")`
