### ISSUE TITLE
citation principles

### ISSUE THREAD

**Issue by dklinges9** [Smithsonian/CCRCN-Data-Library#22]
Correct me if I'm wrong: I believe we established at an earlier point that if a user (in the case I'm thinking of right now, the user is the CCRCN) uses data from a data release with a DOI, the user cites the data release, but not the paper. The paper is only cited if the _interpretation_ of the data is used. Yes?

I am fleshing out citations of hooked data. Deegan 2012 consists of a [study](https://doi.org/10.1038/nature11533) and two data release ([here](https://doi.org/10.6073/pasta/bc041b3546ba4a3730fd391852741620) and [here](https://doi.org/10.6073/pasta/6830381e663fedc52bbdb3c501fdf3ee)). My plan is to include both data release DOIs in our study citations bank, but not the paper's DOI. Correct me if the paper should be included too.

**Comment by mlonneman** [comment]
As long as all of the data is derived from the data releases, the primary citations should be the data releases. The study DOI can be included as a secondary citation.
