### ISSUE TITLE
Need nested citation tables in main synthesis

### ISSUE THREAD

**Issue by HolmquistJ** [Smithsonian/CCRCN-Data-Library#3]
For the main data repository synthesis we need to have a study-level table with study_id indexing multiple studies. We need to be able to handle synthesis studies with multiple citations. 

|study_id | bibtex_info
|:---- |:---- |
| Callaway_2012 | "Original Callaway 2012 paper bibtex info" |
| Callaway_2012 |  "Holmquist 2018 Scientific Reports bibtex info" |
| Adame_2013 | "Original Adame 2013 paper bibtex info" |
| Adame_2013 | "Sanderman 2018 paper bibtex info" |
|etc...|...|

**Comment by mlonneman** [comment]
I can also include a study type column as you suggested in issue 71 in the map repo: 

| study_id | study_type | bibtex_citation |
| :---|:---|:---|
| rovai_2019 | peer reviewed article |  {Rovai et al. Nature Climate Change ...} |
| rovai_2019 | data release | {Rovai et al. CCRCN Data Release Number ...} |
| rovai_2019 | synthesis dataset | {Sanderman et al. ...} |

**Comment by mlonneman** [comment]
I added this to each hook script and compiled them together in the data join script. Columns are: study id, study type, bibliography id, and DOI. The biblio ID will be used in the main app to filter the bibliography according to the user's subset decisions.
