### ISSUE TITLE
guidance updates not reflected on website version

### ISSUE THREAD

**Issue by dklinges9** [Smithsonian/CCRCN-Data-Library#30]
These are changes that I have made to docs/ccrcn_database_structure.csv but NOT to [the posted online guidance](https://serc.si.edu/coastalcarbon/database-structure). I held off on the changing the webpage version because I was told to wait until manager review/group feedback. Nothing too major however.

associated_publications
- bibliography_id 
- study_type -> publication_type, which is more specific and compatible with .bib format

methods_level:
- site_id 
- core_id (methods sometimes are different between sites/cores in a given study)

site_level:
- state 
- watershed

**Comment by jaxinewolfe** [comment]
We now have a methods ID which is shared between the methods and depthseries tables. The associated publications table has also been updated as well (addressed in #64). At the site level, the geography assignment script defines country and administrative division, but not watershed. We'll let that lie for now.
