### ISSUE TITLE
Harmonize site data and geography assignment script

### ISSUE THREAD

**Issue by mlonneman** [Smithsonian/CCRCN-Data-Library#34]
Currently synthesized site data created prior to the geography script is lost. We need to improve integration of geography assignment into the broader synthesis workflow.

**Comment by mlonneman** [comment]
Pre-existing site data preserved after geography assignment. Still need to trigger script during automation process.

**Comment by jaxinewolfe** [comment]
Geography assignment workflow has been updated and only uses core coordinates. Site-level bounding boxes are no longer used in the updated Atlas.
