### ISSUE TITLE
future conflict between study IDs and biblio IDs

### ISSUE THREAD

**Issue by dklinges9** [Smithsonian/CCRCN-Data-Library#6]
At the moment, the CCRCN bibtex entries in this repo have been adjusted so that the IDs of each entry match the study_ID of each dataset in the library (see [this issue in the Map repo](https://github.com/Smithsonian/CCRCN-Data-Library-Map/issues/39) for relevant discussion). We probably want new entries to the CCRCN biblio to be added through some automated process (e.g., the [draft lit compiler I put together](https://github.com/Smithsonian/CCRCN-Data-Library/tree/master/CCRCN_lit_compiler)) by other users....but new bib entries will have IDs that won't match our recommend study_ID format.

What if we just changed our study_ID format so that it matches the biblio ID (if the paper already exists), and the planned biblio ID (if the paper/dataset hasn't been published yet)?

Not of immediate concern (e.g. before the map launches), but I think we should sort this out soon.

**Comment by mlonneman** [comment]
This is only tangentially related and maybe should be its own issue: if we move toward an automated biblio entry, we probably want to make it easy for a user to review it before it's added to the bibliography. When I was adding the citations for datasets that I hooked in, the lit compiler was grabbing wrong information and leaving other fields blank. If I remember correctly, it was struggling particularly with datasets hosted at particular repositories (DSpace and maybe USGS).

**Comment by dklinges9** [comment]
good to know. I only made that shiny app for a quick demonstration, wasn't supposed to be operational yet. But that type of issue sounds like something more inherent to the `cr_cn()` function in the `rcrossref` package

**Comment by mlonneman** [comment]
Yeah it's definitely the cr_cn() function. I pulled that out of the app and was getting those problems.

**Comment by dklinges9** [comment]
I think it's safe to say we're currently stable with handling citations in the library. Good stuff.
