### ISSUE TITLE
Data hook: Weston et al 2020

### ISSUE THREAD

**Issue by jaxinewolfe** [Smithsonian/CCRCN-Data-Library#74]
I have created a Weston et al 2020 folder with the recently published data and a blank template hook script titled Weston et al 2020 is in the data hooks folder (really it was published in 2022 but I suppose that will just be reflected in the data release citation).

@cheneyr @BettsH someone want to write a hook for this cool 😎 data?

**Comment by cheneyr** [comment]
Hi @jaxinewolfe! Just wanted to mention you here- if you have any notes or edits let me know!

**Comment by jaxinewolfe** [comment]
@cheneyr Great job! My only note is that radioisotope activity units are in microcuriesPerGram. Let's check in with Jim about the excess Pb210 model - the _metadata.pdf_ says CIC was used for whole core accretion rate but then says that they compared between multiple methods to confirm that they agreed. In that case, I believe the age_depth_model reference would be CE.
